/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventory;

import java.sql.*;
import java.text.SimpleDateFormat;

import java.util.Date;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Ketchan
 */
public final class stocks_add extends javax.swing.JFrame {

    /**
     * Creates new form stocks_add
     * @throws java.sql.SQLException
     */
    public stocks_add() throws SQLException {
        initComponents();
        Connect();
        setCurrentDate();
        

    }
    
    Connection con;
    PreparedStatement pst;

    
    
    public void Connect() throws SQLException{
        try {
           con = db.getConnection();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void setCurrentDate() {
        date.setVisible(false);
        Date currentDate = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String formattedDate = dateFormat.format(currentDate);
        date.setText(formattedDate);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        item_name = new javax.swing.JTextField();
        item_type = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        item_price = new javax.swing.JSpinner();
        item_quantity = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        item_category = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        add_stock = new javax.swing.JButton();
        date = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ADD NEW STOCK");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(java.awt.SystemColor.controlHighlight);
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 700));

        item_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_typeActionPerformed(evt);
            }
        });

        jLabel1.setText("ITEM NAME");

        jLabel2.setText("ITEM TYPE");

        jLabel4.setText("PRICE");

        item_category.setMaximumRowCount(9);
        item_category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NONE", "Item 2", "Item 3", "Item 4", "Item 5", "Item 6" }));
        item_category.setToolTipText("");

        jLabel5.setText("QUANTITY");

        jLabel3.setText("CATEGORY");

        add_stock.setBackground(new java.awt.Color(102, 153, 255));
        add_stock.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        add_stock.setForeground(new java.awt.Color(255, 255, 255));
        add_stock.setText("ADD STOCK");
        add_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_stockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3))
                    .addComponent(item_category, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(item_price)
                    .addComponent(item_type, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                    .addComponent(item_name)
                    .addComponent(item_quantity, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1))
                    .addComponent(add_stock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(item_name, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(item_type, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(item_price, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(item_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(item_category, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(add_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void add_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_stockActionPerformed
        String itemName = item_name.getText();
            String itemType = item_type.getText();
            Object itemPrice = item_price.getValue();
            Object itemQuantity = item_quantity.getValue();
            Object itemCategory = item_category.getSelectedItem();
            String itemStatus = "In-active";
            String itemDate = date.getText();
            
            
        if( "".equals(itemName)){
            JOptionPane.showMessageDialog(this, "Enter Item Name","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else if( "".equals(itemType)){
            JOptionPane.showMessageDialog(this, "Enter Item Type","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else  if( "0".equals(itemPrice)){
            JOptionPane.showMessageDialog(this, "Input Item Price","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else  if( "0".equals(itemQuantity)){
            JOptionPane.showMessageDialog(this, "Input Item Quantity","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else  if( "None".equals(itemCategory)){
            JOptionPane.showMessageDialog(this, "Select Category","Warning",JOptionPane.WARNING_MESSAGE);
        }
   
        else {
        try {           
            pst = con.prepareStatement("INSERT INTO stocks (item,type,price,quantity,category,status,date)VALUES(?,?,?,?,?,?,?)");
            pst.setString(1,itemName);
            pst.setString(2,itemType);
            pst.setObject(3,itemPrice);
            pst.setObject(4,itemQuantity);
            pst.setObject(5,itemCategory);
            pst.setString(6, itemStatus);
            pst.setString(7,itemDate);
            
            int k = pst.executeUpdate();
            
            if(k==1)
            {
               
                
                JOptionPane.showMessageDialog(this, "Stock Added Successfully");   
                this.setVisible(false);
                item_name.setText("");
                item_type.setText("");
                item_price.setValue(0);
                item_quantity.setValue(0);
                item_category.setSelectedItem("NONE");
                         
                
            }
            else 
            {
                JOptionPane.showMessageDialog(this,"Failed to Add Stock","Error",JOptionPane.ERROR_MESSAGE);
            }
            
            
            
            
// TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(stocks.class.getName()).log(Level.SEVERE, null, ex);
        }
        }                // TODO add your handling code here:
    }//GEN-LAST:event_add_stockActionPerformed

    private void item_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item_typeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stocks_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new stocks_add().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(stocks_add.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_stock;
    private javax.swing.JTextField date;
    private javax.swing.JComboBox<String> item_category;
    private javax.swing.JTextField item_name;
    private javax.swing.JSpinner item_price;
    private javax.swing.JSpinner item_quantity;
    private javax.swing.JTextField item_type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
